apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-server
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: simple-python-server
          image: ghcr.io/hpe-inui-yuko/simple-python-server
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
